services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pixelpal
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend-pixel-pal
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: pixelpal
    depends_on:
      - db
    restart: always
    volumes:
      - ./backend-pixel-pal/uploads:/app/uploads

  frontend:
    build: .
    ports:
      - "4173:80"
    environment:
      - VITE_API_URL=http://backend:4000
    depends_on:
      - backend
    restart: always

volumes:
  db-data:
